eureka:
  client:
    enabled: false
    registerWithEureka: false
  fetchRegistry: false

# Server configuration
server:
  context-path:
  port: ${SERVICE_PORT:8083}

management:
  port: ${MANAGEMENT_PORT:8093}

# Spring properties
spring:
  application:
    name: auth

security:
  ignored: /*.css

jwt:
  sharedSecret: ${HS256_KEY:}

customerService:
  url: ${CUSTOMER_URL:http://127.0.0.1:8082}