replicaCount: 1

image:
  repository: ibmcase/bluecompute-auth
  tag: 0.6.0
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 8083
  internalPort: 8083
  managementPort: 8093
  nodePort: 32383

ingress:
  enabled: false
  hostname: #auth.bluecompute.com
  path: /oauth
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
  enableTLS: false
  TLS:
  - secretName: auth.bluecompute.com
    hosts:
      - auth.bluecompute.com

customer:
  url:

hs256key:
  # If there is an existing secret with the key, provide it here
  secretName:
  secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

global:
  hs256key:
    secretName:
  istio:
    enabled:
    gateway:
      name:

bash:
  image:
    repository: ibmcase/bluecompute-bash-curl-ssl
    tag: latest
    pullPolicy: IfNotPresent

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi

labels:
  app: auth
  version: v1
  tier: backend

securityContext:
  runAsUser: 2000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

istio:
  enabled: false
  # ISTIO_MUTUAL, SIMPLE, DISABLE
  mTLS: ISTIO_MUTUAL
  # LEAST_CONN, ROUND_ROBIN
  loadBalancer: LEAST_CONN
  gateway:
    enabled: false
    name:
    hosts:
      - "auth.bluecompute.com"
    TLS:
      enabled: false
      # SIMPLE, MUTUAL
      mode: SIMPLE
      httpsRedirect: false
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem